<?php

namespace dashboard\dashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichesRepository extends EntityRepository
{
}
