<?php

namespace Elycee\ElyceeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichesRepository extends EntityRepository
{


    public function getCountFiches(){
        $results = $this
            ->createQueryBuilder('p')
            ->select('count(p)')
            ->getQuery()
            ->getSingleScalarResult();
        return $results;


    }

    public function getThreeLastFiches(){
        $results = $this
            ->createQueryBuilder('p')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
        return $results;
    }


    public function persistQuestions($questions,$qcm)
    {
        foreach ($questions as $question) {
            $question->setFiche($qcm);
            foreach ($question->getChoices() as $choice) {
                //$choice->setFiche($qcm);
                $choice->setQuestion($question);

            }

            $this->getEntityManager()->persist($question);
            //echo  dump($question);exit;
            $this->getEntityManager()->flush();
        }
    }


    public function gettheFiches()
    {

        $results = $this
            ->createQueryBuilder('p')
            ->join('p.classes','f')
            ->join('p.status','status')
          //  ->where('f.class_level  =  \'premiere\' ')
            ->andWhere('status.nom = \'publish\'')
            ->getQuery()
            ->getResult();
        return $results;




    }




}
