<?php

namespace Elycee\ElyceeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends EntityRepository
{


    public function getThePost(){
        $results = $this
            ->createQueryBuilder('p')
            ->orderBy('p.date','DESC')
            ->where('p.status = 1')
            ->getQuery()
            ->getResult();
        return $results;
    }


    public function getThreeLastPost(){
        $results = $this
            ->createQueryBuilder('p')
            ->orderBy('p.date','DESC')
            ->where('p.status = 1')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
        return $results;
    }

    public function getCountPost(){
        $results = $this
            ->createQueryBuilder('p')
            ->select('count(p)')
            ->getQuery()
            ->getSingleScalarResult();
        return $results;


    }

}
