<?php

namespace Elycee\ElyceeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends EntityRepository
{


    public function getThePost(){
        $results = $this
            ->createQueryBuilder('p')
            ->orderBy('p.date','DESC')
            ->where('p.status = 1')
            ->getQuery()
            ->getResult();
        return $results;
    }


    public function getThreeLastPost(){
        $results = $this
            ->createQueryBuilder('p')
            ->orderBy('p.date','DESC')
            ->where('p.status = 1')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
        return $results;
    }

    public function getCountPost(){
        $results = $this
            ->createQueryBuilder('p')
            ->select('count(p)')
            ->getQuery()
            ->getSingleScalarResult();
        return $results;


    }


    public function getPostByAuteur($id){
               $results = $this
                        ->createQueryBuilder('p')
                    ->select('p.titre, p.id, p.abstract , p.date','s.nom','a.username')
                    ->join('p.auteur','a')
                    ->join('p.status','s')
                   ->where('a.id = :id')
                    ->setParameter(':id',$id)
                    ->getQuery()
                    ->getResult();
         return $results ;
     }

}
