<?php

namespace Elycee\ElyceeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends EntityRepository
{






}
