<?php

namespace Elycee\ElyceeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function getCountUser(){
        $results = $this
            ->createQueryBuilder('p')
            ->select('count(p)')
            ->getQuery()
            ->getSingleScalarResult();
        return $results;


    }


    public function getUserEleves(){
        $results = $this
            ->createQueryBuilder('p')
            ->select('p.username')
            ->where('p.roles = \'ROLE_STUDENT\'')
            ->getQuery()
            ->getResult();
        return $results;


    }
}
